### ISSUE TITLE
Suppress "refresh button" 

### ISSUE THREAD

**Issue by dominiquehausser** [admin-ch/CovidCertificate-App-Android#371] opened 2021-12-30 10:44 UTC
In my opinion, this button is useless and is there often wrongly used.

Furthermore staff in institutions use the refresh button to check the certificate, not realising that they cannot tell whether it is 2G, 2G+ or 3G or a falsificate one; and it is quite hard, not to say impossible to explain.

The easiest way is to suppress it (as all info about the certificate are written in clear text and normally the user is already aware about the validity of his own certificate.

Alternative, if you do not want to suppress it, may be a new menu at the bottom of the page with the others.

**Comment by goebelUB** [comment] 2022-01-04 18:17
Duplicate of #295

**Closed by goebelUB** 2022-01-04 18:17 UTC
