### ISSUE TITLE
Remove annoying check button

### ISSUE THREAD

**Issue by hackerONrails** [admin-ch/CovidCertificate-App-Android#330] opened 2021-11-16 08:48 UTC
It is quite ugly and unhygienic to have foreigners touching on my phone. Please remove the "self checking" button, it is not a real feature, more like a burden. Who knows, perhaps already infections happend because of that?!
"Checkers" should do the check using the "Checkers App".

Thanks.

**Comment by goebelUB** [comment] 2021-11-16 08:50
Duplicate of #295

**Closed by goebelUB** 2021-11-16 08:50 UTC
