### ISSUE TITLE
Crash on PDF import

### ISSUE THREAD

**Issue by gyeoman** [admin-ch/CovidCertificate-App-Android#237] opened 2021-08-14 17:12 UTC
I have a mobile phone (android 7.0) and tablet (android 6.0).

Both phone and tablet have swiss covid cert app (v 2.3.0) installed from the google play store. 

Both fail to import the Swiss vaccine certificate downloaded from vacme. 

An error is reported on the tablet: COVID certificate format invalid. (PDF/NCF)

No error is reported on the phone - the app just closes. 

I am able to use the "Scan QR code" option on the tablet to read the QR code from the camera and store it in the app.  This option does not work on my phone but my phone does have a terrible camera. 

I am able to view the pdf on my laptop, phone and tablet.  The QR code is clearly visible.  The QR code must be a valid code because the camera on my tablet can read the QR code using the app.

**Comment by panmau** [comment] 2021-08-15 09:36
This seems to be a duplicate of #203

**Comment by goebelUB** [comment] 2021-08-15 17:43
Indeed, likely a duplicate.

We know that with some configurations the PDF import isn't perfect, and we're working on improving it.
I agree that the error message is confusing ("invalid format" rather than "could not read QR code"). We'll improve that as well.

> No error is reported on the phone - the app just closes.

This is interesting. So you open the app, click "Import PDF", then select a PDF - what exactly happens then? Does it return to Covid Cert? Does Covid Cert crash? What phone/manufacturer is it?

**Comment by gyeoman** [comment] 2021-08-15 18:42
It's a Moto G4 running Android 7.0.

All that happens on my phone is that I get a popup box that says:

    "Covid cert keeps stopping

    x Close App

    ! Send feedback"

I can select either on "x" or "!"  on the touchscreen.

The problem I face is that I can't imort from pdf on my phone but I also can't get the QR code to scan from the phone's camera.  That means I'm stepping back to the 90s with my paper printout :)

**Closed** 2021-08-18 21:11 UTC
Labels: bug
