### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [admin-ch/CovidCertificate-App-Android#260] opened 2021-09-15 14:43 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'CovidCertificate'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve ch.ubique.gradle:ubdiag-android:7.0.2.
     Required by:
         project :
      > No matching variant of ch.ubique.gradle:ubdiag-android:7.0.2 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.0.2' but:
          - Variant 'apiElements' capability ch.ubique.gradle:ubdiag-android:7.0.2 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0.2')
          - Variant 'runtimeElements' capability ch.ubique.gradle:ubdiag-android:7.0.2 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.0.2')
```

Could you please take a look? Thanks!

**Comment by thgoebel** [comment] 2021-09-15 15:06
Yep, Java 11. I'm already making a PR, just fighting to get one of the many way to run F-Droid server working...

**Comment by goebelUB** [comment] 2021-09-15 19:12
C.f. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9775

**Comment by goebelUB** [comment] 2021-10-01 20:47
It would be great if the above PR could be merged soonish. Then F-Droid bot can copy a working build script when it picks up v2.6.0, which I am going to tag for the bot sometime late this Sunday (2021-10-03).

That said, the build for v2.5.0 will still fail because of the "Unknown Maven" repo. Hence the PR doesn't remove the `disable:` line for v2.5.0.
However the offending repo [has been removed](c1b1637eaf2f2cb910aebeff09c4051047309c7f) in v2.6.0 so unless I missed something (or there are other reproducibility issues...) that version has good chances of making it onto F-Droid again! 🤞

**Comment by goebelUB** [comment] 2021-10-07 19:31
Here's a new MR: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9885
It doesn't quite reproduce. I would highly appreciate any help as to why one APK/ZIP is deflated, while the other is not. I can't quite see what is different between our's and F-Droid's build environment.

**Comment by linsui** [comment] 2021-10-10 14:48
The build failed. Could you please take a look? https://monitor.f-droid.org/builds/log/ch.admin.bag.covidcertificate.wallet/2600#site-footer Thanks!

**Comment by linsui** [comment] 2021-10-11 01:32
Maybe @obfusk ? Could you please take a look?

**Comment by goebelUB** [comment] 2021-11-01 07:21
Thanks again @linsui for merging by MR with lightning speed!

I'll track bringing F-Droid back into the main release (instead of separate releases) in #304.

**Closed by goebelUB** 2021-11-01 07:21 UTC

**Comment by linsui** [comment] 2021-11-01 07:30
Thanks!
